[package]
name = "vello_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

# Vello CPU is experimental - dependencies will be added when stable
[dependencies]
vello_cpu = "0.0.4"
kurbo = "0.12"
peniko = "0.5"
